/**
 * gen-bible.ts — CLI wiring for the Opus overlay generator.
 *
 * Reads the consumer's gatekit.json qa config + qa-map.generated.json,
 * calls generateBible with a real OpenRouter completion, then writes the
 * owned overlay (qa-map.overlay.ts) or a draft file.
 *
 * Usage:
 *   npm run qa:gen-bible [-- [--force] [--model <slug>] [--routes-only]]
 *
 * Flags:
 *   --force         Overwrite qa-map.overlay.ts even if it already exists
 *   --model <slug>  Override the OpenRouter model slug (default: cfg.bibleModel ?? anthropic/claude-opus-4)
 *   --routes-only   Skip the LLM step; just run gen-qa-map and exit
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

// Deployed layout: this file lives at {sentinel}/scripts/gen-bible.ts;
// shared libs are at {sentinel}/src/lib/ — so all imports use ../src/lib/.
import { generateBible } from "../src/lib/bible-gen.js";
import { getClient } from "../src/lib/openrouter.js";
import { extractRoutes, type QaConfig, type GeneratedFile } from "../src/lib/route-extract.js";
import type { QaOverlay } from "../src/lib/qa-map.js";

// ── paths ────────────────────────────────────────────────────────────────────

const SENTINEL_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OVERLAY_PATH = path.resolve(SENTINEL_DIR, "src/lib/qa-map.overlay.ts");
const DRAFT_PATH   = path.resolve(SENTINEL_DIR, "src/lib/qa-map.overlay.draft.ts");
const GENERATED_PATH = path.resolve(SENTINEL_DIR, "src/lib/qa-map.generated.json");

// ── helpers ───────────────────────────────────────────────────────────────────

function findRepoRoot(startDir: string): string {
  let dir = startDir;
  while (true) {
    if (existsSync(path.join(dir, "gatekit.json"))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return process.cwd();
}

function loadGatekitQaConfig(repoRoot: string): QaConfig {
  const gkPath = path.join(repoRoot, "gatekit.json");
  if (!existsSync(gkPath)) {
    // Sensible fallback
    return { routing: "next-pages" };
  }
  const raw = JSON.parse(readFileSync(gkPath, "utf8")) as Record<string, unknown>;
  if (!raw.qa || typeof raw.qa !== "object") return { routing: "next-pages" };
  return raw.qa as QaConfig;
}

/** Serialize a QaOverlay as a TS module with an OWNED-FILE banner. */
function serializeOverlay(overlay: QaOverlay): string {
  const json = JSON.stringify(overlay, null, 2);
  return `\
// ============================================================
// OWNED FILE — Opus-drafted, refine me.
// This overlay was generated by \`npm run qa:gen-bible\`.
// Edit domains, preconditions, and out-of-scope as needed,
// then commit. Re-running with --force will overwrite.
// ============================================================
import type { QaOverlay } from "./qa-map.js";

export const OVERLAY: QaOverlay = ${json};
`;
}

// ── main ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const force = args.includes("--force");
  const routesOnly = args.includes("--routes-only");

  const modelIdx = args.indexOf("--model");
  const modelOverride = modelIdx !== -1 ? args[modelIdx + 1] : undefined;

  const repoRoot = findRepoRoot(path.dirname(fileURLToPath(import.meta.url)));
  const cfg = loadGatekitQaConfig(repoRoot);

  // If --routes-only, just regenerate the routes JSON and exit.
  if (routesOnly) {
    const generated = extractRoutes(repoRoot, cfg);
    writeFileSync(GENERATED_PATH, JSON.stringify(generated, null, 2) + "\n", "utf8");
    console.log(`[gen-bible] --routes-only: wrote ${generated.routes.length} routes to ${path.relative(SENTINEL_DIR, GENERATED_PATH)}`);
    return;
  }

  // Load the committed generated file.
  let generatedFile: GeneratedFile;
  if (existsSync(GENERATED_PATH)) {
    generatedFile = JSON.parse(readFileSync(GENERATED_PATH, "utf8")) as GeneratedFile;
  } else {
    // Regenerate on-the-fly if the JSON is missing.
    generatedFile = extractRoutes(repoRoot, cfg);
  }

  if (generatedFile.routes.length === 0) {
    console.warn("[gen-bible] Warning: no routes found. Run `npm run qa:gen-map` first or check routing config.");
  }

  // Build the real OpenRouter completer.
  const client = getClient();
  const modelSlug = modelOverride ?? cfg.bibleModel ?? "anthropic/claude-opus-4";

  const complete = async (p: { system: string; user: string }): Promise<string> => {
    const response = await client.chat.completions.create({
      model: modelSlug,
      messages: [
        { role: "system", content: p.system },
        { role: "user",   content: p.user },
      ],
      // Note: not all OpenRouter models honor json_object response_format (some 400
      // or return plain prose). parseOverlay's code-fence stripping is the fallback.
      response_format: { type: "json_object" },
    });
    const text = response.choices[0]?.message?.content;
    if (!text) throw new Error("[gen-bible] Model returned empty response");
    return text;
  };

  console.log(`[gen-bible] Calling ${modelSlug} via OpenRouter…`);

  const { overlay, problems } = await generateBible({
    rootDir: repoRoot,
    cfg,
    generated: generatedFile,
    complete,
  });

  if (problems.length > 0) {
    console.error("[gen-bible] Overlay has problems — NOT writing (fix or regenerate routes first):\n");
    for (const p of problems) {
      console.error(`  • ${p}`);
    }
    process.exit(1);
  }

  const ts = serializeOverlay(overlay);

  const overlayExists = existsSync(OVERLAY_PATH);

  if (!overlayExists || force) {
    writeFileSync(OVERLAY_PATH, ts, "utf8");
    console.log(`[gen-bible] ✓ Wrote ${path.relative(SENTINEL_DIR, OVERLAY_PATH)}`);
    console.log("[gen-bible] Review and refine the overlay, then commit it.");
  } else {
    writeFileSync(DRAFT_PATH, ts, "utf8");
    console.log(`[gen-bible] qa-map.overlay.ts already exists (use --force to overwrite).`);
    console.log(`[gen-bible] Draft written to ${path.relative(SENTINEL_DIR, DRAFT_PATH)}`);
    console.log("[gen-bible] Merge the draft into qa-map.overlay.ts manually, then commit.");
  }
}

main().catch((err) => {
  console.error("[gen-bible] Fatal:", err instanceof Error ? err.message : err);
  process.exit(1);
});
