import OpenAI from "openai";
import type { Usage } from "./types.js";

/** A model the reviewer can run, keyed by the alias used in a `/review` comment. */
export interface ModelSpec {
  /** Alias typed in `/review <key>` and used to namespace this model's comments. */
  key: string;
  /** OpenRouter model slug actually called. */
  slug: string;
  /** Human-readable label shown in the review. */
  label: string;
  /** USD per 1M input tokens (NaN for an ad-hoc slug with unknown pricing). */
  input: number;
  /** USD per 1M output tokens. */
  output: number;
}

/**
 * Registered models, keyed by the alias used in a `/review <key>` comment.
 * Pricing is USD per 1M tokens, from OpenRouter's published rates.
 */
export const MODELS: Record<string, ModelSpec> = {
  glm: { key: "glm", slug: "z-ai/glm-5.2", label: "GLM 5.2", input: 1.2, output: 4.1 },
  opus: { key: "opus", slug: "anthropic/claude-opus-4.8", label: "Claude Opus 4.8", input: 5, output: 25 },
  gpt: { key: "gpt", slug: "openai/gpt-5.5", label: "GPT-5.5", input: 5, output: 30 },
  gemini: { key: "gemini", slug: "google/gemini-3.1-pro-preview", label: "Gemini 3.1 Pro", input: 2, output: 12 },
  deepseek: { key: "deepseek", slug: "deepseek/deepseek-v4-pro", label: "DeepSeek V4 Pro", input: 0.435, output: 0.87 },
  minimax: { key: "minimax", slug: "minimax/minimax-m3", label: "MiniMax M3", input: 0.3, output: 1.2 },
  mimo: { key: "mimo", slug: "xiaomi/mimo-v2.5-pro", label: "Xiaomi MiMo 2.5 Pro", input: 0.435, output: 0.87 },
  kimi: { key: "kimi", slug: "moonshotai/kimi-k2.7-code", label: "Kimi K2.7 Code", input: 0.612, output: 3.069 },
};

/** Cheap, capable default for non-interactive jobs (release-changelog fallback,
 *  QA-memory synthesis). NOT the `/review` default — see REVIEW_DEFAULT_MODEL_KEY. */
export const DEFAULT_MODEL_KEY = "glm";

/** The model `/review` uses when the comment names none. Opus by default for the
 *  strongest review; override per-comment with `/review glm`, `/review gpt`, … */
export const REVIEW_DEFAULT_MODEL_KEY = "opus";

/**
 * Fallback chain used by non-interactive jobs (e.g. the release changelog),
 * in order, when the primary model errors or is rate-limited. OpenRouter's
 * `models` request array routes this server-side: it tries each slug in turn
 * and only bills the one that answers. GLM 5.2 stays first to match the other
 * jobs' default; the rest are progressively stronger backstops.
 */
export const FALLBACK_KEYS = ["glm", "deepseek", "gemini", "gpt"] as const;

/** OpenRouter slug chain for fallback routing, `primaryKey` first, de-duplicated. */
export function fallbackSlugs(primaryKey: string = DEFAULT_MODEL_KEY): string[] {
  const ordered = [primaryKey, ...FALLBACK_KEYS.filter((k) => k !== primaryKey)];
  const seen = new Set<string>();
  const slugs: string[] = [];
  for (const key of ordered) {
    const slug = MODELS[key]?.slug;
    if (slug && !seen.has(slug)) {
      seen.add(slug);
      slugs.push(slug);
    }
  }
  return slugs;
}

export function getClient(): OpenAI {
  const apiKey = process.env.OPENROUTER_API_KEY;
  if (!apiKey) {
    throw new Error("OPENROUTER_API_KEY is not set");
  }
  return new OpenAI({
    apiKey,
    baseURL: "https://openrouter.ai/api/v1",
    defaultHeaders: {
      "HTTP-Referer": "https://github.com/PaulCailly/tens0r",
      "X-Title": "tens0r code review",
    },
  });
}

/** A model key, sanitised so it is safe inside an HTML-comment marker and a regex. */
export function safeKey(m: ModelSpec): string {
  return m.key.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
}

/**
 * A plausible raw OpenRouter slug: `provider/model`, slug-safe chars only, a
 * single `/`. Deliberately strict so a URL or markdown link in the comment
 * (e.g. `[code](https://claude.ai/code)`, `https://x/y`) is NOT mistaken for a
 * model — those contain `:`, `[`, `]`, `(`, `)` and fail this. A real variant
 * suffix like `:free`/`:nitro` is still allowed in the model part.
 */
const RAW_SLUG_RE = /^[a-z0-9][\w.-]*\/[a-z0-9][\w.:-]*$/i;

/**
 * Resolve the models a `/review …` comment asks for.
 * - no model named        → [REVIEW_DEFAULT_MODEL_KEY] (Opus)
 * - `all`                 → every registered model
 * - known aliases         → those models, in order, de-duplicated
 * - a raw `provider/slug` → an ad-hoc model (pricing unknown)
 * Only the FIRST line selects models: a `/review` comment routinely carries a
 * trailing footer or prose on later lines (e.g. an auto-appended
 * `_Generated by [Claude Code](https://claude.ai/code)_`), whose markdown-link
 * token would otherwise be parsed as a bogus slug and 400 the whole review.
 * Unknown bare words / non-slug tokens are ignored. If the first line named
 * models but none resolved (a typo, e.g. `/review gtp`), fall back to the CHEAP
 * default — not the pricier empty-comment default — so a typo can't silently run
 * the costliest model.
 */
export function resolveModels(commentBody: string): ModelSpec[] {
  const firstLine = commentBody.split(/\r?\n/)[0] ?? "";
  const after = firstLine.trim().replace(/^\/review\b/i, "").trim();
  const tokens = after.split(/\s+/).filter(Boolean).map((t) => t.toLowerCase());

  if (tokens.length === 0) return [MODELS[REVIEW_DEFAULT_MODEL_KEY]];
  if (tokens.includes("all")) return Object.values(MODELS);

  const out: ModelSpec[] = [];
  const seen = new Set<string>();
  for (const t of tokens) {
    if (seen.has(t)) continue;
    if (MODELS[t]) {
      seen.add(t);
      out.push(MODELS[t]);
    } else if (RAW_SLUG_RE.test(t)) {
      // A raw OpenRouter slug, e.g. "google/gemini-3-pro" — run it, cost unknown.
      seen.add(t);
      out.push({ key: t, slug: t, label: t, input: NaN, output: NaN });
    }
    // else: unknown bare word or non-slug token (URL, markdown), ignored.
  }
  // Named-but-unresolved (a typo) → cheap default, never the pricier empty default.
  return out.length > 0 ? out : [MODELS[DEFAULT_MODEL_KEY]];
}

/** The priciest model in the set — picks who writes the cross-analysis summary. */
export function mostExpensive(models: ModelSpec[]): ModelSpec {
  const cost = (m: ModelSpec) => (Number.isFinite(m.input) && Number.isFinite(m.output) ? m.input + m.output : -1);
  return models.reduce((best, m) => (cost(m) > cost(best) ? m : best), models[0]);
}

/** Estimate the USD cost of a run from token usage. Null when the model is unpriced. */
export function estimateCost(usage: Usage, model: ModelSpec): number | null {
  if (!Number.isFinite(model.input) || !Number.isFinite(model.output)) return null;
  return (usage.input_tokens * model.input + usage.output_tokens * model.output) / 1_000_000;
}
